# Remove the version line
services:
  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    command: server /data

volumes:
  minio_data:
